# Viper Language Extension for Zed
id = "viper"
name = "Viper"
description = "Viper support."
version = "0.1.0"
schema_version = 1
repository = "https://github.com/revengerwizard/zed-viper"
authors = ["Wizard"]

[grammars.viper]
repository = "https://github.com/revengerwizard/tree-sitter-viper"
rev = "8d25f958a35d8f0e08a796ab5063a7051994116d"
