# Viper Language Extension for Zed
id = "viper"
name = "Viper"
description = "Viper support."
version = "0.1.0"
schema_version = 1
repository = "https://github.com/revengerwizard/zed-viper"
authors = ["Wizard"]

[grammars.viper]
repository = "https://github.com/revengerwizard/tree-sitter-viper"
rev = "14837ca4c9e7066ebafc92fab61c7ec9ca444d0f"